<?php
return [
    'STU_PREFIX' => 'stu',
    'typeGender' => [
            1       => 'Male',
            2       => 'Female',
            //3       => 'TransGender',
    ],
    'typeStatus' => [
            1       => 'Active',
            2       => 'Inactive',
    ],
    'statusIconColor' => [
            'on'    => [
                'icon'  => 'heroicon-c-check',
                'color' =>'success',
            ],
            'off'   => [
                'icon'  => 'heroicon-o-x-mark',
                'color' =>'gray',
            ],
    ],
    'typeStudentStatus' => [
            1 => "Active",
            2 => "Inactive",
            3 => "Discontinued",
            4 => "Relieved",
    ],
    'typeBlood'  => [
        1 => "A-",
        2 => "A+",
        3 => "B-",
        4 => "B+",
        5 => "AB-",
        6 => "AB+",
        7 => "O-",
        8 => "O+",
        99 => "OTHER",
    ],
    'typeReligion'  => [
        1 => "Hindu",
        2 => "Muslim",
        3 => "Sikh",
        4 => "Christian",
        99 => "OTHER",
    ],
    'typeGroup'  => [
        1 => "Main",
        2 => "Sub",
    ],
    'typeMedium'  => [
        1 => "English",
        2 => "Hindi",
    ],
    'typeFoodChoice'    => [
        1 => "Veg",
        2 => "Non Veg",
        3 => "Eggetarian",
    ],
    'typeAdmission'  => [
        1 => "New",
        2 => "Old",
    ],
    'typeClassCode'  => [
        1 => "I",
        2 => "II",
        3 => "III",
        4 => "IV",
        5 => "V",
        6 => "VI",
        7 => "VII",
        8 => "VIII",
        9 => "IX",
        10 => "X",
        11 => "XI",
        12 => "XII",
        13 => "NURSERY",
        14 => "LKG",
        15 => "UKG",
        16 => "PREP",
    ],
    'typeSection'    => [
        1 => "A",
        2 => "B",
        3 => "C",
    ],
    'typeCaste'  => [
        1 => "General",
        2 => "OBC",
        3 => "SC",
        4 => "ST",
        99 => "OTHER",
    ],
    'indianStates' => [
        'AP' => 'Andhra Pradesh',
        'AR' => 'Arunachal Pradesh',
        'AS' => 'Assam',
        'BR' => 'Bihar',
        'CT' => 'Chhattisgarh',
        'GA' => 'Goa',
        'GJ' => 'Gujarat',
        'HR' => 'Haryana',
        'HP' => 'Himachal Pradesh',
        'JK' => 'Jammu and Kashmir',
        'JH' => 'Jharkhand',
        'KA' => 'Karnataka',
        'KL' => 'Kerala',
        'MP' => 'Madhya Pradesh',
        'MH' => 'Maharashtra',
        'MN' => 'Manipur',
        'ML' => 'Meghalaya',
        'MZ' => 'Mizoram',
        'NL' => 'Nagaland',
        'OR' => 'Odisha',
        'PB' => 'Punjab',
        'RJ' => 'Rajasthan',
        'SK' => 'Sikkim',
        'TN' => 'Tamil Nadu',
        'TG' => 'Telangana',
        'TR' => 'Tripura',
        'UP' => 'Uttar Pradesh',
        'UT' => 'Uttarakhand',
        'WB' => 'West Bengal',
        'AN' => 'Andaman and Nicobar Islands',
        'CH' => 'Chandigarh',
        'DN' => 'Dadra and Nagar Haveli',
        'DD' => 'Daman and Diu',
        'LD' => 'Lakshadweep',
        'DL' => 'National Capital Territory of Delhi',
        'PY' => 'Puducherry'
    ],

];
